version: '3'
services:
  api:
    container_name: nimgur-api-dev
    image: "${ECR_REGISTRY}/${ECR_REPOSITORY}:${GITHUB_SHA}"
    ports:
      - "8041" # map the service port to 8040 for staging
    environment:
      - NODE_ENV=prod
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - BUCKET_ARN=${BUCKET_ARN}
      - CDN_HOST=${CDN_HOST}
