name: Nimgur API Workflow
on:
  push:
    branches: [ master, dev ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - id: build-push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: nimgur-api
          IMAGE_TAG: ${{ github.sha }}

        run: |
          cd api
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      - id: deploy-dev
        uses: appleboy/ssh-action@v0.1.4
        if: github.ref == 'refs/heads/dev'
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          passphrase: ${{ secrets.DEPLOY_SSH_KEY_PASSPHRASE }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}
          script: |
            export GITHUB_SHA=${{ github.sha }}
            export ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
            export ECR_REPOSITORY=nimgur-api
            cd /var/www/not.gd/nimgur/api/deployment/
            aws ecr get-login-password | docker login --username AWS --password-stdin "$ECR_REGISTRY"
            docker-compose --env-file .env -f docker-compose-dev.yml up --force-recreate --build -d api
      - id: deploy
        uses: appleboy/ssh-action@v0.1.4
        if: github.ref == 'refs/heads/master'
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          passphrase: ${{ secrets.DEPLOY_SSH_KEY_PASSPHRASE }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}
          debug: true
          script: |
            export GITHUB_SHA=${{ github.sha }}
            export ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
            export ECR_REPOSITORY=nimgur-api
            cd /var/www/not.gd/nimgur/api/deployment/
            aws ecr get-login-password | docker login --username AWS --password-stdin "$ECR_REGISTRY"
            docker-compose --env-file .env -f docker-compose-live.yml up --force-recreate --build -d api
